### ISSUE TITLE
带有端口的url无法正常调通

### ISSUE THREAD

**Issue by zhangxiang0319** [zhangmingfeng/egg-axios#3]
## 现象   

如果url带端口则无法正常调用,如 http://www.demo.com:8080/path

## 推测

经过url模块解析后的host是带端口的,后面又重复加了port.应将host替换为替换为hostname

**Comment by zhangmingfeng** [comment]
@zhangxiang0319 是存在问题，已经修复，谢谢！你可以直接PR的
